SIGNOS = {
 "aries": dict(n="Aries", e="♈", f="21 mar – 19 abr", el="Fuego", p="Marte", c="Cardinal", pi="Rubí",
  fort="Valentía, iniciativa y energía", ret="Impaciencia e impulsividad", comp=["Leo", "Sagitario", "Géminis"],
  d="El pionero del zodiaco: directo, competitivo y siempre listo para empezar algo nuevo."),
 "tauro": dict(n="Tauro", e="♉", f="20 abr – 20 may", el="Tierra", p="Venus", c="Fijo", pi="Esmeralda",
  fort="Constancia, lealtad y sentido práctico", ret="Terquedad y apego a la comodidad", comp=["Virgo", "Capricornio", "Cáncer"],
  d="Amante de la estabilidad, los placeres sencillos y las cosas bien hechas."),
 "geminis": dict(n="Géminis", e="♊", f="21 may – 20 jun", el="Aire", p="Mercurio", c="Mutable", pi="Ágata",
  fort="Curiosidad, ingenio y comunicación", ret="Dispersión e indecisión", comp=["Libra", "Acuario", "Aries"],
  d="Mente rápida y sociable, siempre con una pregunta nueva o una conversación en marcha."),
 "cancer": dict(n="Cáncer", e="♋", f="21 jun – 22 jul", el="Agua", p="Luna", c="Cardinal", pi="Perla",
  fort="Empatía, intuición y protección", ret="Sensibilidad excesiva y nostalgia", comp=["Escorpio", "Piscis", "Tauro"],
  d="Profundamente emocional y familiar; cuida de los suyos con enorme ternura."),
 "leo": dict(n="Leo", e="♌", f="23 jul – 22 ago", el="Fuego", p="Sol", c="Fijo", pi="Ámbar",
  fort="Carisma, generosidad y liderazgo", ret="Orgullo y necesidad de reconocimiento", comp=["Aries", "Sagitario", "Libra"],
  d="Brilla con luz propia; es cálido, creativo y le encanta inspirar a los demás."),
 "virgo": dict(n="Virgo", e="♍", f="23 ago – 22 sep", el="Tierra", p="Mercurio", c="Mutable", pi="Zafiro",
  fort="Análisis, disciplina y servicio", ret="Perfeccionismo y autocrítica", comp=["Tauro", "Capricornio", "Cáncer"],
  d="Observador y metódico; encuentra la manera de mejorar todo lo que toca."),
 "libra": dict(n="Libra", e="♎", f="23 sep – 22 oct", el="Aire", p="Venus", c="Cardinal", pi="Cuarzo rosa",
  fort="Diplomacia, estética y equilibrio", ret="Dudas y miedo al conflicto", comp=["Géminis", "Acuario", "Leo"],
  d="Busca armonía en todo: en las relaciones, en la belleza y en la justicia."),
 "escorpio": dict(n="Escorpio", e="♏", f="23 oct – 21 nov", el="Agua", p="Plutón", c="Fijo", pi="Obsidiana",
  fort="Intensidad, determinación y magnetismo", ret="Celos y desconfianza", comp=["Cáncer", "Piscis", "Virgo"],
  d="Misterioso y apasionado; no hace nada a medias y siente todo con profundidad."),
 "sagitario": dict(n="Sagitario", e="♐", f="22 nov – 21 dic", el="Fuego", p="Júpiter", c="Mutable", pi="Turquesa",
  fort="Optimismo, libertad y honestidad", ret="Imprudencia y falta de tacto", comp=["Aries", "Leo", "Acuario"],
  d="Explorador por naturaleza: viajes, ideas grandes y mucha fe en el futuro."),
 "capricornio": dict(n="Capricornio", e="♑", f="22 dic – 19 ene", el="Tierra", p="Saturno", c="Cardinal", pi="Granate",
  fort="Ambición, responsabilidad y paciencia", ret="Rigidez y exceso de trabajo", comp=["Tauro", "Virgo", "Escorpio"],
  d="Constructor paciente que escala metas paso a paso hasta llegar a la cima."),
 "acuario": dict(n="Acuario", e="♒", f="20 ene – 18 feb", el="Aire", p="Urano", c="Fijo", pi="Amatista",
  fort="Originalidad, independencia y visión", ret="Distancia emocional y rebeldía", comp=["Géminis", "Libra", "Sagitario"],
  d="Mente innovadora que piensa distinto y se preocupa por el futuro de todos."),
 "piscis": dict(n="Piscis", e="♓", f="19 feb – 20 mar", el="Agua", p="Neptuno", c="Mutable", pi="Aguamarina",
  fort="Imaginación, compasión y sensibilidad", ret="Evasión y dificultad para poner límites", comp=["Cáncer", "Escorpio", "Capricornio"],
  d="Soñador y artista del zodiaco; percibe emociones que otros no notan."),
}

COLORES = ["Azul", "Verde", "Dorado", "Rojo", "Violeta", "Blanco", "Naranja", "Turquesa", "Rosa", "Plateado"]

BANCOS = {
 "general": ["Hoy es un buen momento para retomar algo que habías dejado pendiente.",
  "La paciencia te dará mejores resultados que la prisa.", "Una conversación inesperada puede abrirte una nueva perspectiva.",
  "Confía en tu intuición, pero revisa los detalles importantes.", "Los astros favorecen los cambios pequeños pero constantes.",
  "Tu energía está alta: aprovéchala para avanzar en tus metas.", "Quizás sientas ganas de ordenar tu entorno, y te hará bien.",
  "Alguien cercano necesitará tu apoyo; tu presencia marcará la diferencia."],
 "amor": ["Dedica tiempo de calidad a quien quieres.", "Sé claro con lo que sientes; la sinceridad suma.",
  "Si estás solo/a, una sorpresa puede aparecer en lo cotidiano.", "Un gesto pequeño fortalecerá tu relación.",
  "Evita discutir por cosas pasajeras.", "Escuchar más que hablar será tu mejor estrategia.",
  "Es buen día para reconciliarte con alguien especial.", "Atrévete a dar el primer paso."],
 "trabajo": ["Organiza tus prioridades y avanza paso a paso.", "Una buena idea merece ser compartida.",
  "Evita discusiones innecesarias y enfócate en resultados.", "Un proyecto detenido puede reactivarse pronto.",
  "Pide ayuda si la necesitas; trabajar en equipo rinde más.", "Tu constancia será notada por quienes importan.",
  "Aprende algo nuevo: te abrirá puertas más adelante.", "Cuida los plazos y evita dejar todo para último momento."],
 "dinero": ["Revisa tus gastos antes de hacer una compra grande.", "Se asoma una oportunidad de ingreso extra; analízala bien.",
  "Ahorrar un poco hoy te dará tranquilidad mañana.", "Evita prestar dinero sin acuerdos claros.",
  "Es buen momento para planificar tu presupuesto.", "Un pago pendiente se resolverá si insistes con calma.",
  "Invierte en tu formación; es la mejor inversión.", "No te dejes llevar por compras impulsivas."],
 "salud": ["Dormir bien será clave para rendir mejor.", "Toma más agua y haz pausas durante el día.",
  "Una caminata corta despejará tu mente.", "Cuida tu espalda y tu postura al trabajar.",
  "Reduce las pantallas antes de dormir.", "Dedica unos minutos a respirar profundo.",
  "Come con calma y prefiere alimentos frescos.", "Tu estado de ánimo mejora si te rodeas de gente querida."],
 "consejo": ["Respira hondo antes de responder.", "Haz primero lo más difícil del día.",
  "Agradece algo antes de dormir.", "Di no a lo que no te aporta.", "Sonríe: abre más puertas de las que imaginas.",
  "Termina una tarea pendiente hoy.", "Escribe tus metas; verlas ayuda a cumplirlas."],
 "frase": ["Cada día es una nueva oportunidad.", "Lo que siembras hoy, lo cosechas mañana.",
  "La calma también es una forma de fuerza.", "Tu actitud define tu rumbo.", "Los grandes cambios empiezan con un pequeño paso.",
  "Confía en el proceso; todo llega a su tiempo.", "Eres más capaz de lo que crees."],
}